### ISSUE TITLE
Datasource 404 with docker images containing docker/ in name

### ISSUE THREAD

**Issue by skycaptain** [renovatebot/renovate#15030]
### How are you running Renovate?

Self-hosted

### If you're self-hosting Renovate, tell us what version of Renovate you run.

32.17.0

### Please select which platform you are using if self-hosting.

GitLab self-hosted

### If you're self-hosting Renovate, tell us what version of the platform you run.

14.9.2

### Was this something which used to work for you, and then stopped?

It used to work, and then stopped

### Describe the bug

We're using Artifactory to proxy/cache public docker images. In our Dockerfiles and Gitlab CI configuration we reference them with `artifactory.mycompany.com/docker/python:3` instead of `python:3` or `artifactory.mycompany.com/docker/renovate/renovate:32.17.0-slim` instead of `renovate/renovate:32.17.0-slim`. Somewhere between 31.35.0 and 31.68.4 a change was introduced that stops updating these images, as fetching new docker image tags fails:

```
DEBUG: Datasource 404 (repository=[redacted])
       "datasource": "docker",
       "packageName": "artifactory.mycompany.com/docker/renovate/renovate",
       "url": "https://artifactory.mycompany.com/v2/renovate/renovate/tags/list?last=10000&n=10000"
```

With 31.35.0 it worked:

```
DEBUG: getLabels(https://artifactory.mycompany.com/, docker/renovate/renovate, latest) (repository=[redacted])
DEBUG: getManifestResponse(https://artifactory.mycompany.com/, docker/renovate/renovate, latest) (repository=[redacted])
DEBUG: found labels in manifest (repository=[redacted])
       "labels": {
         "maintainer": "Rhys Arkins <rhys@arkins.net>",
         "name": "renovate",
         "org.opencontainers.image.licenses": "AGPL-3.0-only",
         "org.opencontainers.image.source": "https://github.com/renovatebot/renovate",
         "org.opencontainers.image.url": "https://renovatebot.com/",
         "org.opencontainers.image.version": "31.71.1"
       }
```

Images from other Artifactory repositories of the same form (e.g. `artifactory.mycompany.com/my-repo/my-project/my-image`) still work, so I guess renovate is now dropping the `docker/` part from the URL.

```
$ curl -u user:pass "https://artifactory.mycompany.com/v2/renovate/renovate/tags/list?last=10000&n=10000"
{
  "errors" : [ {
    "status" : 404,
    "message" : "Not Found"
  } ]
}

$ curl -u user:pass "https://artifactory.mycompany.com/v2/docker/renovate/renovate/tags/list?last=10000&n=10000"
  {
    "name" : "renovate/renovate",
    "tags" : [ "sha256-518b1532a581c54b88c06dc9022e7ea87c62c601ac4231382d49384c9282e3a2.sig",...
```

The issue still exists on the latest 32.17.0 version.

### Relevant debug logs

<details><summary>Logs</summary>

```
Copy/paste any log here, between the starting and ending backticks
```

</details>

### Have you created a minimal reproduction repository?

No reproduction repository

**Comment by mmaeller** [comment]
Hi @skycaptain ,

See https://github.com/renovatebot/renovate/issues/5894#issuecomment-1083044661

Furthermore the limit of 10.000 tags has been hit recently, so the docker pagination won't work properly with the wrong docker access method.
There are some issues in Jfrog jira. 
https://www.jfrog.com/jira/browse/RTFACT-18971?focusedCommentId=65615&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-65615

**Comment by skycaptain** [comment]
@mmaeller Thanks for the hint. Havn't found that one when I search for related issues.

Changing the Docker Access Method is not an option we would like to consider at the moment, as this would mean changing thousands of lines of code (among other practicalities), which worked well before. Other docker tools (skopeo and alike) work also fine.

I'm still wondering why only `docker` is swallowed, and other repository names still work fine.

Regarding the pagination issue: Although they closed the issue you linked without any comment, the issue might have been fixed with recent releases of Artifactory. Using skopeo I get the same result for the renovate/renovate image as for our proxied image.

**Comment by viceice** [comment]
we need this to debug. the image doesn't need to exist, as the failure should be visiting before.

**Comment by mmaeller** [comment]
> @mmaeller Thanks for the hint. Havn't found that one when I search for related issues.
> 
> Changing the Docker Access Method is not an option we would like to consider at the moment, as this would mean changing thousands of lines of code (among other practicalities), which worked well before. Other docker tools (skopeo and alike) work also fine.
> 
> I'm still wondering why only `docker` is swallowed, and other repository names still work fine.
> 
> Regarding the pagination issue: Although they closed the issue you linked without any comment, the issue might have been fixed with recent releases of Artifactory. Using skopeo I get the same result for the renovate/renovate image as for our proxied image.

Hi, the issue isn't fixed. Our company has an open ticket at JFrog related to this issue, but it doesn't look like that it may be fixed in near future.

Your virtual repository is named "docker", right?
So like in the mentioned JFrog ticket renovate sends a request to 
```
GET /v2/docker/renovate/renovate/tags/list?n=10000
```
The returned amount of tags is currently greater than 10000, so Artifactory appends an additional reponse header named "Link".
It's value is
```
</v2/renovate/renovate/tags/list?last=10000&n=10000>; rel="next"
```
Renovate uses pagination for up to 20 pages to fetch the tags.
As you might see the returned path is incorrect. Artifactory does not relate to the virtual repository. The correct path should look like this.
```
</v2/docker/renovate/renovate/tags/list?last=10000&n=10000>; rel="next"

```
So the next request fails and renovate can't update the desired docker image. That's no renovate issue. It's an Artifactory issue.

Renovate has set a limit of pagination for 10000. Perhaps skopeo has a higher initial limit or even none?
See rarkins statement in this issue https://github.com/renovatebot/renovate/issues/9176

**Comment by skycaptain** [comment]
@mmaeller Thank you very much for your explaination; now the penny dropped. You are right, Artifactory sends `Link: </v2/renovate/renovate/tags/list?last=10000&n=10000>; rel="next"` in its response header. And this seems like to be issue why fetching the tags fails.

> Renovate has set a limit of pagination for 10000.

Since you said, you wouldn't expect a fix from Jfrog anytime soon, would it make sense to make the pagination limit configurable? On private Artifactory instances, we AFAIK do not have any API restrictions. E.g. `GET https://artifactory.mycompany.com/v2/docker/renovate/renovate/tags/list?n=0` returns all tags.

> Perhaps skopeo has a higher initial limit or even none?

It has none:

```
DEBU[0000] GET https://artifactory.mycompany.com/v2/docker/renovate/renovate/tags/list
```

**Comment by mmaeller** [comment]
That's why I linked to [#9176](https://github.com/renovatebot/renovate/issues/9176#issuecomment-800938496)
This would likely be a feature request to disable the limit at
https://github.com/renovatebot/renovate/blob/main/lib/modules/datasource/docker/index.ts#L677
