### ISSUE TITLE
v37 planning

### ISSUE THREAD

**Issue by viceice** [renovatebot/renovate#23911]
### Describe the proposed change(s).

- [x] #16359
- [x] #23779
  - [x] #24542
- [x] #22744
  - [x] #22749

### Related issues

- #21134

**Comment by HonkingGoose** [comment]
@rarkins wanted us to have "config migration via Dependency Dashboard" [^1] _before_ making config migration the default behavior. [^2]

I'll let you maintainers prioritize what's going in `v37`. 😉 

[^1]: #19783
[^2]: #16359

**Comment by rarkins** [comment]
I've dropped config migration from default from this list because it's not ready. See https://github.com/renovatebot/renovate/issues/16359#issuecomment-1688202419

**Comment by HonkingGoose** [comment]
The issue title and `v37` label are outdated now that you guys released `v37`. You should bump the title and label to `v38`. 😉

**Comment by rarkins** [comment]
Done!

**Comment by wanisfahmyDE** [comment]
Hi @viceice, we installed the renovatebot app directly in github, how can we know which version is being used and where can we track that?
Asking because a change like mentioned here https://github.com/renovatebot/renovate/issues/23326#issuecomment-1662967088 might cause a breaking change for us eventually
Many thanks

**Comment by viceice** [comment]
we've migration code, so no worries. 

renovate version can be seen on mend developer dashboard linked from PR body

**Comment by wanisfahmyDE** [comment]
@viceice apologies, I looked everywhere in our mend developer dashboard but I still cannot find it.
Do you mind if you drop a screenshot example?
Thank you <3

**Comment by viceice** [comment]
you need to check the logs for one of the latest runs

**Comment by wanisfahmyDE** [comment]
Found it, thanks alot

**Comment by HonkingGoose** [comment]
@viceice can you put issue #16359 back on your todo list again? :wink: It's currently crossed out.

`@rarkins` wants to enable the config migration by default in `v38`, see last comment in issue:

- #16359

**Comment by HonkingGoose** [comment]
@viceice can you update your top post of this issue? Some of your todo's landed in `v37`. 😉

**Comment by viceice** [comment]
added a new issue
- #27992
