### ISSUE TITLE
Force push to a PR's base branch causes incorrect "PR has been edited" comment

### ISSUE THREAD

**Issue by edmorley** [renovatebot/renovate#3220]
**What Renovate type are you using?**
Renovate GitHub App

**Describe the bug**
A Renovate PR targetting `master` had an incorrect "this PR has been edited" message, after `master` was updated via a force push.

**To Reproduce**

1.  Have Renovate open a PR against master, eg https://github.com/mozilla/treeherder/pull/4649
2.  Force push to `master` to fix an issue in the most recent commit
3. Watch the Renovate PR for changes

**Expected behavior**
For Renovate to see that the master revision being targetted no longer exists, or else to pick up on the GitHub event that appears in the PR history, and  as such know to rebase against `master` automatically, and leave a comment saying the PR has been edited.

**Screenshots**

![screenshot_2019-02-16 update dependency react-select to v2 4 0 by renovate pull request 4649 mozilla treeherder](https://user-images.githubusercontent.com/501702/52897696-5ffe3f80-31cf-11e9-83a9-c9fa46fac105.png)

**Comment by rarkins** [comment]
We need to review our logic for determining if a PR has been "edited" and see if we can easily tell the difference between a PR that has actually been edited vs the case where a force push was done to the base branch.

**Comment by edmorley** [comment]
With #3221 fixed this is lower priority for us :-) (Also hopefully needing to force push should be a rare event!)

**Comment by felixfbecker** [comment]
I am seeing this not on every force push to master but on regular pushes to master 😣

https://github.com/sourcegraph/sourcegraph-typescript/pull/100#issuecomment-466771980

These emails came in for every Renovate PR (all freshly rebased) right after I pushed to master:

![image](https://user-images.githubusercontent.com/10532611/53299630-21a2f900-383d-11e9-88b2-1ad8763112de.png)

**Comment by rarkins** [comment]
@felixfbecker your problem is related to the lockfile-update option. I’m hoping to refactor it this week to fix.

**Comment by rarkins** [comment]
I think this likely still happens, but at least these days it's much easier to request a rebase/retry to resolve it, and hopefully force pushes to base branches are rare? Will leave this open in case we work out a resolution for it, but for now with the way we use git to determine modification status
