### ISSUE TITLE
Go mod update from v1 to v2 doesn't update anything

### ISSUE THREAD

**Issue by ViRb3** [renovatebot/renovate#9492]
**What Renovate type, platform and version are you using?**
- Public Renovate Github Bot

**Describe the bug**

A continuation of #9127. I have a Go module repo that, in its `Go.mod` file, references:
```
github.com/gofiber/fiber v1.14.6
```
The latest version of `fiber` is `v2.7.1`. When Renovate sends a PR, it looks like this:

https://github.com/ViRb3/renovate-bug-mrr/pull/4/files
```diff
-require github.com/gofiber/fiber v1.14.6
+require (
+	github.com/gofiber/fiber v1.14.6
+	github.com/valyala/fasthttp v1.18.0 // indirect
+	golang.org/x/sys v0.0.0-20201210223839-7e3030f88018 // indirect
+)
```

It seems like the only change made here is the introduction of the `indirect` dependencies. The main dependency is not upgraded from `v1` to `v2`. There are also no import changes in any of the code files.

**Relevant debug logs**
N/A

**Have you created a minimal reproduction repository?**

Yes. It can be found [here](https://github.com/ViRb3/renovate-bug-mrr/) and the bad PR is [here](https://github.com/ViRb3/renovate-bug-mrr/pull/4).

**Comment by ViRb3** [comment]
@56KBs Since you were working on the same repo in the previous issue, I am allowing myself to tag you here. Apologies for any disturbance.

**Comment by 56KBs** [comment]
@ViRb3 thanks for the tag - Happy to look into the issue - Especially if I may have been the one to cause it 🙈 

From a quick glance, I think the reason that this is still an issue is because #9144 introduced a new, optional `postUpdateOption` which provides the functionality, if you the following to your renovate.json:

```json
  "gomod": {
    "postUpdateOptions": ["gomodUpdateImportPaths"]
  },
```

It should start working.

**Comment by rarkins** [comment]
@56KBs thanks. I got mixed up and thought it was enabled by default, but I was confusing it with the tidying which is implicitly enabled instead. If you have been running/testing they functionality for a couple of weeks now we could consider making it default enabled in the next major release we're about to ship?

**Comment by 56KBs** [comment]
> @56KBs thanks. I got mixed up and thought it was enabled by default, but I was confusing it with the tidying which is implicitly enabled instead. If you have been running/testing they functionality for a couple of weeks now we could consider making it default enabled in the next major release we're about to ship?

I've been running it since it merged across around 8 Go repositories, everything has been fine so far however I think we've only experienced a single major version update in that time. Confirmation that this ticket is resolved would give some more confidence it's not just my system that is totally fine :)

**Comment by ViRb3** [comment]
Hello @rarkins @56KBs,

My apologies for the super delayed response, I actually didn't realize you were waiting for me to test that config in `renovate.json`. I can confirm that after making [this change](https://github.com/ViRb3/renovate-bug-mrr/commit/214c406b052f91c4bc8cc8767462d937c4117d36), Renovate finally properly updates my dependency from v1 to v2: https://github.com/ViRb3/renovate-bug-mrr/pull/4

I will be very grateful if you could enable this config by default so that I don't have to update dozens of config files.

Thanks!

**Comment by rarkins** [comment]
@ViRb3 I recommend you use [config presets](https://docs.renovatebot.com/config-presets/) for your repositories so that you can make centralized changes easily

**Comment by ViRb3** [comment]
@rarkins Note taken, thanks! Why close this issue though? Import upgrading still does not work by default.

**Comment by rarkins** [comment]
What does your second to last comment mean then?

**Comment by ViRb3** [comment]
With a default config, which is what someone unaware of this issue would have, imports are not upgraded. Only after manually adding the following in `renovate.json`the issue is resolved:

```json
  "gomod": {
    "postUpdateOptions": ["gomodUpdateImportPaths"]
  }
```

Unless the user finds this github issue and performs the undocumented config file change, import upgrading won't work. As you suggested a few comments up, it would be great if this config is the default, and that's what I was trying to request.

**Comment by rarkins** [comment]
![image](https://user-images.githubusercontent.com/6311784/118401121-b4215400-b664-11eb-89ea-bc531c9abf1b.png)

This a documented feature, not undocumented. Behavior is currently intentional, and this was never a bug.

**Comment by ViRb3** [comment]
My apologies, I was on my phone when I concluded that this feature was undocumented and I didn't give it a thorough look. Looking from the computer now I can confirm that it is there and clearly documented. As long as that's the case, I am perfectly happy with the solution. Thanks a lot for the help!
